### ISSUE TITLE
Add support for Kafka as a MQ

### ISSUE THREAD

**Issue by seiflotfy** [iron-io/functions#155]

**Comment by denismakogon** [comment]
@seiflotfy Do we really think that Kafka looks like desired MQ option? There are couple reasons:
- you can't delete messages from topic (there's message retention timeout, around 7 days)
- you can't rewrite message because broker will increase message offset

So, how would we implement reservation and deletion?

**Comment by denismakogon** [comment]
As discussed with @seiflotfy Kafka doesn't look like good MQ candidate due to its specialities. 

Reopen this if necessary.
