### ISSUE TITLE
install falied using mysql database with utf8 charset

### ISSUE THREAD

**Issue by heww** [iron-io/functions#655]
```shell
time="2017-10-27T09:38:02Z" level=info msg="MySQL dialed" max_idle_connections=30 
time="2017-10-27T09:38:02Z" level=fatal msg="Error initializing datastore." error="Error 1071: Specified key was too long; max key length is 767 bytes" 
```

**Comment by c0ze** [comment]
hello @heww ,

Assuming you are following [mysql docs](https://github.com/iron-io/functions/blob/master/docs/operating/databases/mysql.md) . 

It is difficult to diagnose a problem with so little information, but it seems your problem is about indexing a UTF8 field in MySQL. I would advise checking [stackoverflow](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes) for similar problems.  If you have identified this as a IronFunctions specific problem, please share some information.

Thanks !
